USE mysql;
FLUSH PRIVILEGES;

GRANT ALL ON *.* TO '$MARIADB_ADMIN_USER'@'%' identified by '$MARIADB_ADMIN_PWD' WITH GRANT OPTION;
GRANT ALL ON *.* TO '$MARIADB_ADMIN_USER'@'localhost' identified by '$MARIADB_ADMIN_PWD' WITH GRANT OPTION;
SET PASSWORD FOR '$MARIADB_ADMIN_USER'@'localhost'=PASSWORD('$MARIADB_ADMIN_PWD');

DROP DATABASE IF EXISTS test;
FLUSH PRIVILEGES;

CREATE DATABASE $MARIADB_DB CHARACTER SET utf8 COLLATE utf8_general_ci;
CREATE USER '$MARIADB_USER'@'%' IDENTIFIED by '$MARIADB_PWD';
CREATE USER '$MARIADB_USER'@'localhost' IDENTIFIED by '$MARIADB_PWD';

GRANT ALL PRIVILEGES ON $MARIADB_DB.* TO '$MARIADB_USER'@'%';
GRANT ALL PRIVILEGES ON $MARIADB_DB.* TO '$MARIADB_USER'@'localhost';
FLUSH PRIVILEGES;