version: '3'

services:
    nginx:
        image: nginx:mine
        build:
          context: ./requirements/nginx/
        container_name: nginx
        networks:
          - network
        ports:
          - "443:443"
        restart: always

networks:
  network: